### ISSUE TITLE
no content

### ISSUE THREAD

**Issue by andyComeOn** [Stevenzwzhai/vue-mobile-application#1]
u item no content show,  show  loading. ask  u  , is it right?

**Comment by Stevenzwzhai** [comment]
You should do your own server to provide data

**Comment by andyComeOn** [comment]
teacher:  u  at  China or USA?

**Comment by Stevenzwzhai** [comment]
China

**Comment by q27488** [comment]
At `src/api/API.js` ，`baseURL: 'http:....',`   should use myself server to provide data?  change the baseURL?

**Comment by Stevenzwzhai** [comment]
yes,or you can use mockjs
